//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelTripProje1.Models.Sinifler1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN
    {
        public int ID { get; set; }
        public string KULANICI { get; set; }
        public string SIFRE { get; set; }
    }
}
